### ISSUE TITLE
Always use the Speak-Layout for all SPEAK Pages

### ISSUE THREAD

**Issue by ivan-korshun** [Sitecore-Community/Sitecore.Speak.Guidance#10]
The following is written in [PageDefinitionItems.md](https://github.com/Sitecore-Community/Sitecore.Speak.Guidance/blob/gh-pages/Application%20Development/Page%20Development/PageDefinitionItems.md):

> 2. Always use the Speak-Layout for all SPEAK Pages.

**Speak-EmptyLayout** seems to be preferred for sub-pages.
For example, for LoadOnDemandPanel or Repeater.

**Comment by dervalp** [comment]
Is sub-pages a page? Maybe we should define what is a Speak Sub-Page and what is the use of it?

**Comment by ivan-korshun** [comment]
LoadOnDemandPanel control renders an item and inserts the rendered markup into a page.
This item (rendered by LoadOnDemandPanel) is a sub-page.

**Comment by kerrybellerose** [comment]
The top of the file states:

The following guidelines apply to applications created by Sitecore for release as part of the Sitecore platform.

I agree with Pierre that a sub-page is not an application page.  

I agree that guidance related to when to use a Speak Sub-Page makes sense.  

I'd like someone to propose guidelines (pull request is OK, I can clean up the language).

**Comment by ivan-korshun** [comment]
I have created a pull request with the proposal.
So I close this issue.
