### ISSUE TITLE
Do check in "commented out" code

### ISSUE THREAD

**Issue by ivan-korshun** [Sitecore-Community/Sitecore.Speak.Guidance#12]
The following is written in [JavaScript.md](https://github.com/Sitecore-Community/Sitecore.Speak.Guidance/blob/gh-pages/Application%20Development/PageCode/JavaScript.md):

> -  Do check in "commented out" code.

What does it mean? What should I check in commented out code?

**Comment by dervalp** [comment]
I will close this issue as you can see it is now written
- Do NOT check in "commented out" code.

See here: https://github.com/Sitecore-Community/Sitecore.Speak.Guidance/blame/gh-pages/Application%20Development/PageCode/JavaScript.md
