### ISSUE TITLE
Parameters Template: default parameters

### ISSUE THREAD

**Issue by ivan-korshun** [Sitecore-Community/Sitecore.Speak.Guidance#13]
The following is written in [ParametersTemplate.md](https://github.com/Sitecore-Community/Sitecore.Speak.Guidance/blob/gh-pages/Component%20Development/Items/ParametersTemplate.md):

> - Create a `__Standard Values` item for the Parameters Template and set default values for parameters there.

Default values should be also set in the Default Parameters field of the appropriate View Rendering item.

**Comment by dervalp** [comment]
I think we need to have one way to set default value for a parameter otherwise it would become messy.
It is not because we can do it in both ways that we need to define both in convention.

> Default values should be also set in the Default Parameters field of the appropriate View Rendering item.

Could you explain what would be the advantages by using that instead of __standardvalues ? To me, it is just another way but I may be wrong.

**Comment by ivan-korshun** [comment]
We have to set a default value in both `__Standard Values` item and `Default Parameters` field.

When you add a rendering to a layout, `__Standard Values` are not taken into account. Only `Default Parameters` field is used to set default values of the rendering.

On the other hand, `__Standard Values` are used when you create a Data Source item for a rendering (control).

**Comment by dervalp** [comment]
ok great. Then I agree, we need to specify that in the guideline.

**Comment by kerrybellerose** [comment]
## How does this look?
- Create a `__Standard Values` item for the Parameters Template and use it to set default values for configuration items.
- Set default values for component parameters set in the Layout Details in the `Default Parameters` field of the appropriate View Rendering item.

**Comment by dervalp** [comment]
good to me.

**Comment by kerrybellerose** [comment]
Done.
