### ISSUE TITLE
PageDefinitionItems: Adding Page-Script-File below a page

### ISSUE THREAD

**Issue by MaxReimerNielsen** [Sitecore-Community/Sitecore.Speak.Guidance#17]
In Experience Analytics this was a really bad way of including JavaScripts. We did it for the first half year, but when we ended up with 50 pages, and we then had to add/remove/edit location of scripts, then we had to do it on all the pages.

What we ended up with, was a Require in each of our components instead, to include the files needed, even though the same JavaScript is used across different components.

I honestly do not know what to write in this bullet, because it depends a lot on how the Application is setup.

**Comment by dervalp** [comment]
I think the Page-Script-File is maybe more useful for 3rd Party than for having the application code. 

What do you think if we mention that in our guideline?

**Comment by MaxReimerNielsen** [comment]
Sounds like a great solution.

**Comment by kerrybellerose** [comment]
OK, so I will change the text of this line to:
1. Use the Page-Script-File item to reference a 3rd party JavaScript file from your page.
