### ISSUE TITLE
Speak-DashboardPage vs DashboardPage

### ISSUE THREAD

**Issue by MartinSvarrer** [Sitecore-Community/Sitecore.Speak.Guidance#2]
It currently states in the fifth item about definition items:
> Create the application Dashboard page, which is the application's default initial page and is also known as the root page, directly under the application folder. Use the name Dashboard and the Speak-DashboardPage branch.

Is /Templates/Speak-DashboardPage recommended over /templates/branches/applications/DashboardPage?

**Comment by kerrybellerose** [comment]
> Is /Templates/Speak-DashboardPage recommended over /templates/branches/applications/DashboardPage?

No.  

The branch is based on the template, and includes required components (such as the PageCode), so the branch is appropriate.

**Comment by MartinSvarrer** [comment]
Okay, thanks for the reply. We need to update the description then to recommend DashboardPage instead of Speak-DashboardPage.
Will close this issue once page is updated.

**Comment by kerrybellerose** [comment]
Page updated.
