### ISSUE TITLE
UTF.SPEAK. Testing framework for UI automation.

### ISSUE THREAD

**Issue by andrewsolod** [Sitecore-Community/Sitecore.Speak.Guidance#23]
Hi!
I'd like to add information about using UTF.SPEAK testing framework for UI test automation. Would it be possible to add appropriate section for that? 

Here the parts for that section:
Introduction.
Main features.
Multi-browser support.
Basic set up for Speak Application Wrapper and UI Auto-test C# projects.
Writing wrappers for SPEAK Applications using UTF.SPEAK.
UI Auto-test project setup.

**Comment by kerrybellerose** [comment]
> Would it be possible to add appropriate section for that?

Yes, I can do this, although I'd like to make sure that we agree on where it makes sense to create this section.

So far, the guidance is divided into Application Development and Component Development.  I mostly imagine that most teams will review only one of these two sections (mostly Application Development for Application Teams, mostly Component Development for the Platform UI team).

Therefore, I expect that it would be best to separate the testing guidance in the same way (Testing Applications under the Application Development section and a similar section for components).  

Do you agree that this makes sense?

It might help me as well to see your current draft documents.

**Comment by andrewsolod** [comment]
I agree to have separated Testing guidance between Testing Application and Testing Components. 
Also we probably have to separate Testing guidance on functional and automation sections.

**Comment by kerrybellerose** [comment]
OK, I have sent a new draft to Andrey with suggested changes.  We will continue working this offline.
