### ISSUE TITLE
[Dialog Definition Items] Page-StyleSheet-File item section could be supplemented

### ISSUE THREAD

**Issue by eugenegrebeshkov** [Sitecore-Community/Sitecore.Speak.Guidance#24]
The following section from [PageDefinitionItems](https://github.com/Sitecore-Community/Sitecore.Speak.Guidance/blob/gh-pages/Application%20Development/Page%20Development/PageDefinitionItems.md) can be supplemented:

> Use the Page-StyleSheet-File item to add a CSS file to your page.

Not only Page-StyleSheet-File item can be used, but also Page-StyleSheet-Folder item in order to add more then one stylesheet to the page.

**Comment by kerrybellerose** [comment]
OK, how about if I add the following bullet to that file:
- Use the Page-StyleSheet-Folder to reference a folder containing CSS files to associate with your page.

**Comment by eugenegrebeshkov** [comment]
Looks good to me.
