### ISSUE TITLE
Code Guidelines for Razor Views

### ISSUE THREAD

**Issue by eugenegrebeshkov** [Sitecore-Community/Sitecore.Speak.Guidance#25]
In this section I would add the guidance about html attributes, e.g. you should separate the parts of the attribute with “-“, for example “data-sc-property”. Also it would be great to mention that all the data attributes should be started from "data-sc-"

**Comment by kerrybellerose** [comment]
OK, how about these bullets:
- Prefix all data attribute names with "data-sc-"
- Use dash (-) to separate words in attribute names (for example, "data-sc-property-name")

**Comment by eugenegrebeshkov** [comment]
I'm OK with that!

**Comment by kerrybellerose** [comment]
Done.
