### ISSUE TITLE
Dialogs

### ISSUE THREAD

**Issue by ivan-korshun** [Sitecore-Community/Sitecore.Speak.Guidance#8]
The following is written in [DialogDefinitionItems.md](https://github.com/Sitecore-Community/Sitecore.Speak.Guidance/blob/gh-pages/Application%20Development/Page%20Development/DialogDefinitionItems.md):

> The following guidelines apply to dialogs created by Sitecore for release as part of the Sitecore platform.
> 1. Use the **Speak-DialogPage** template for all Sitecore dialogs.
> 2. Always use the Speak-Layout for all Sitecore dialogs.

We have 2 types of dialogs: Content Editor dialogs and dialogs provided by **DialogWindow** control.
This guide is true for the first type of dialogs.
But the second type (DialogWindow) should use **Speak-BasePage** template and **Speak-EmptyLayout**.

**Comment by dervalp** [comment]
We should maybe split that component in 2.

**Content Editor Dialog**

Dialog which is open by the content editor.

1)Use the Speak-DialogPage template for all Sitecore dialogs.
2)Always use the Speak-Layout for all Sitecore dialogs.

**DialogWindow control**

Dialog which are generally in the SPEAK Page using the DialogWindow control.
1. Use the Speak-DialogPage template for all Sitecore dialogs.
   2 .Always use the Speak-EmptyLayout for all DialogWindow .

Do you agree?

**Comment by kerrybellerose** [comment]
> Dialog which is open by the content editor.

I think the Content Editor is too specific.  Eventually, other legacy applications will start opening SPEAK dialogs as well (Experience Editor, Marketing Center, etc.).

Am I understanding correctly that our guidance is different for dialogs opened by SPEAK application pages as opposed to our old Sheer applications?

Perhaps that is the differentiation:

**Dialog Opened by a Sheer Application**

**Dialog Opened by a SPEAK Application**

**Comment by ivan-korshun** [comment]
Just a small correction:

> Dialog which are generally in the SPEAK Page using the DialogWindow control.
> 1. Use the ~~Speak-DialogPage~~**Speak-BasePage** template for all Sitecore dialogs. 2 .Always use the Speak-EmptyLayout for all DialogWindow .

**Comment by dervalp** [comment]
If they are all sheer applications (to be honest, I have no idea). I am fine with those titles.

Maybe in Sheer Application, giving some examples (Content Editor, Experience Editor,...).

**Comment by kerrybellerose** [comment]
## Do you guys agree with this end result?

The following guidelines apply to dialogs _created by Sitecore for release as part of the Sitecore platform_.

### Sheer Application Dialogs

Use the following guidelines for dialogs displayed by legacy Sheer applications (such as the Content Editor, Experience Editor, and so on).
1. Use the **Speak-DialogPage** template.
2. Use the **Speak-Layout** for the dialog page.

### SPEAK Application Dialogs

Use the following guidelines for dialogs displayed by SPEAK based applications (such as 
1. Use the **Speak-BasePage** template.
2. Use the **Speak-EmptyLayout** for the dialog page.

**Comment by dervalp** [comment]
I looks good.

**Comment by kerrybellerose** [comment]
Done.

**Comment by stijnherreman** [comment]
> Use the following guidelines for dialogs displayed by SPEAK based applications (such as 

The sentence is cut off. Was there supposed to come anything after that?
