### ISSUE TITLE
 Always use one of the predefined page branches when creating a new page

### ISSUE THREAD

**Issue by ivan-korshun** [Sitecore-Community/Sitecore.Speak.Guidance#9]
The following is written in [PageDefinitionItems.md](https://github.com/Sitecore-Community/Sitecore.Speak.Guidance/blob/gh-pages/Application%20Development/Page%20Development/PageDefinitionItems.md):

> 1. Always use one of the predefined page branches when creating a new page (DashboardPage, ListPage, or TaskPage).

Why do we need to limit developers with these branches?
Why they cannot create their own branches?

For example, we created the SpeakDemoPage branch in our Demo package. It is becase original branches do not fulfil our needs. Without a new branch we have to repeat the same actions each time when a demo page is created.

**Comment by kerrybellerose** [comment]
> Why do we need to limit developers with these branches?

The top of this page has the following information:

The following guidelines apply to applications created by Sitecore for release as part of the Sitecore platform.

The UX guideline state that Sitecore application pages must be of one of these three types.

The example you give is not a Sitecore application, so not following this guideline is acceptable.

**Comment by ivan-korshun** [comment]
If we faced with need of a custom branch, then other teams may face with this need too (other teams = teams creating applications to be released as part of Sitecore).
This rule may force developers to repeat some manual operations for several pages.

**P.S.** Feel free to close the issue if you still disagree.

**Comment by kerrybellerose** [comment]
> If we faced with need of a custom branch, then other teams may face with this need too

This will require special approval by the UX team and management.  I will close this issue, as we do not want to encourage applications to do things that are against UX policies.
